### ISSUE TITLE
Enhancement: Use cotire for unity build

### ISSUE THREAD

**Issue by ViteFalcon** [Darelbi/Infectorpp#7]
I just saw that you're using a custom unity-build CMake file. You could leverage [cotire](https://github.com/sakra/cotire) (Compile Time Reducer) instead.

**Comment by Darelbi** [comment]
Nice library I'll dig into that (to be honest the current script, wich however does its dirty work very well, is there just to make "advertising" for my 3d engine XD ).. seems also actually that cotire increase build time so I'll not use it for now

**Comment by Ogritor** [comment]
On Visual Studio by default a pre-compiled header is used if you import sourcefiles directly

**Comment by ViteFalcon** [comment]
I believe that isn't the case, since Visual Studio has no information about which of the source files acts as the precompiled source file. Can you explain a bit more about what you mean?

**Comment by Ogritor** [comment]
VS has a nice and well defined policy: for each project it adds all headers of that project to a stdafx.h file.
So if your solution have 1 library and 1 project using the library you will have 2 precompiled headers, wich is also what you need (usually).

**Comment by ViteFalcon** [comment]
That's not done by default, if that's what you're suggesting. Also `stdafx.h` file only gets added when you create a project using their standard templates (or if you generate your project by saying that `stdafx.h` is your precompiled header). When projects are generated using CMake, precompiled headers are not defined. This issue is to enable that feature.

P.S.: In Visual Studio, you can make any (single) header and source file a precompiled header and precompiled source. In my projects, if I want to use PCH feature, I name them explicitly as `PrecompiledHeader.h` and `PrecompiledSource.h`.
